#!/usr/bin/env sh

weather(){
   curl -s https://wttr.in/ | head -n 7
}

gnu(){
   echo gnu/linux/$(ls /usr/bin/ | sort | awk '{print $1}' | tr '\e\n' '/' )
}

vol(){
   echo Volume: $(pamixer --get-volume-human)
}
wd(){
   aria2c $(xclip -o -s -c)
}
c(){
   cd "$(< /home/lu/.cache/ctemp | fzf --reverse --height 70%)" 
}

cr(){
   find ~ -type d > /home/lu/.config/ctemp | lolcat
}

scl(){ 
   mpv "https://soundcloud.com/pwningnoobs1337/likes" 
}

m(){
   cd hdd/Music ; mpv "$(fzf)" ; cd
}

mf(){
   mpv --no-video $HOME/hdd/Music/"$(ls $HOME/hdd/Music | fzf)"
}

fzfu(){
   package=$(pacman -Q | fzf) 
   echo "You've chosen to uninstall $package"
   cutpackage=$(echo "$package" | cut -d' ' -f1)
   yay -Rns $cutpackage
}



#--------------------------------------

# Aliases
alias i="jp2a --color"
alias rr="doas reflector --verbose --protocol https --country Sweden,Denmark,Netherlands,France,Germany,Finland --sort rate --save /etc/pacman.d/mirrorlist"
alias up="doas pacman -Syu"
alias y="yay" 
alias sc="systemctl"
alias yt="ytfzf"
alias sm="sudo mount"
alias ta="tmux attach"
alias shred="shred -uvfzn3"
alias rb="systemctl reboot"
alias un="sudo apt remove"
alias mnv="/usr/bin/mpv --no-video"
alias fa="ffplay -nodisp"
alias ytdlpv="yt-dlp f 248+251"
alias ytdlpa="yt-dlp -f 251-dash"
alias fs="import -window root screenshot.png"
alias i3c="vi $HOME/.config/i3/config"
alias alc="vim $HOME/.config/alacritty/alacritty.yml"
alias au="nvim /home/lu/.local/bin/autostartrc"
alias xsr="doas nvim /usr/local/bin/xsrdwm"
alias fc="nvim /home/lu/.config/zsh/aliasrc"
alias pmv="$HOME/Fatty/code/playmusicvideo"
alias dm="cd ; dmenu_run"
alias py="clear ; python"
alias x="startx"
alias wii="dolphin-emu-nogui"
alias mci="sudo make clean install"
alias cl="clear"
alias clc="clear"
alias lc="clear"
alias enc="emacs -nw"
alias e="emacsclient -nw"
alias eg="emacsclient "emacs""
alias chmod="chmod -v"
alias rm="rm -v -rf --preserve-root"
alias mv="mv -v"
alias cp="cp -rv"
alias rne="rename -v"
alias grep="grep --color"
alias egrep="grep --color -E"
alias ls="exa --group-directories-first"
alias sl="exa --group-directories-first"
alias sls="exa --group-directories-first"
alias ll="exa --group-directories-first -l"
alias dwmconf="vim /home/lu/Fatty/dots/dwm-test/config.h"
alias shutoff="systemctl poweroff"
alias alrc="vim /home/lu/.aliasrc"
alias lb="cd /home/lu/.local/bin/"
alias src="cd /home/lu/.local/src/"
alias ub="cd /usr/bin"
alias cd,="cd .."
alias cd,,="cd ../.."
alias cd,,,="cd ../../.."
alias br="vim $HOME/.bashrc"
alias zr="vim $HOME/.zshrc"
alias ac="vim $HOME/.config/alacritty/alacritty.yml"

alias ki="kitty +kitten icat"
alias kc="vim $HOME/.cache/wal/colors-kitty.conf"

#alias mpv="devour mpv"
#alias sxiv="devour sxiv"
#alias vimb="devour vimb"
alias bt="sudo bluetoothctl"
alias nn="firejail --noprofile --net=none"
alias th="cd /home/lu/Fatty/Games"
alias xev="xev -rv"

bloat(){
   echo $(pacman -Q | wc -l) ct Gold
}

nf(){
   neofetch
}

alias visc='vim .config/vis/config'
alias "pc"="doas vim /etc/polybar/config.ini"
alias dwmc='cd /home/lu/.local/src/dwm && vim config.h'
alias ulb="cd /usr/local/bin"

vis60(){
   sed -i 's/240/60/g' $HOME/.config/vis/config
}
vis240(){
   sed -i 's/60/240/g' $HOME/.config/vis/config
}
alias vis="vis60 ; vis"

s(){
   doas vim $(find /home/lu/.local/bin/ /usr/bin /usr/local/bin /home/lu/.config | fzf --reverse --height 50% --prompt "Edit: ")
}

se(){
   emacs $(find /home/lu/.local/bin/ /usr/bin /usr/local/bin /home/lu/.config | fzf --reverse --height 50% --prompt "Edit: ")
}

fm(){
cd /home/lu/hdd/Music
mnv "$(find | fzf --height 50% --reverse --prompt "Play Music : ")"
}

alias wp="vim $HOME/.local/src/dwm-pywal/config.h"
alias h="< $HOME/.cache/zshhistory | sort | uniq | fzf"
alias hc="< $HOME/.cache/zshhistory | sort | uniq | fzf | xclip -se c"
